### PR TITLE
Refresh strace to 6.7, rebase the patch

### PR DESCRIPTION
**Pull request by zyga**
Tested locally on amd64

### CODE REVIEW

**Comment by dilyn-corner** [comment]
We should also makes sure it works on other arches -- s390x was a tricky one for me last time I did a build iirc

lgtm tho!

**Comment by zyga** [comment]
@dilyn-corner how did you test s390x? Did you get a shell on a real box or was it qemu?

**Comment by dilyn-corner** [comment]
You think I'm testing? 🤣 
I didn't test anything except AMD64 -- I have no idea how we're testing other architectures in general.

**Comment by zyga** [comment]
Having worked on FOSS for about two decades, I'm still missing an s390x but I have, er, too many other computers.

**Pull request merged**
